name: Publish Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip extension
        run: zip -r extension.zip . -x "*.git*" ".github/*" "*.DS_Store"

      - name: Upload to Chrome Web Store
        uses: maxlaverse/chrome-webstore-upload@v1
        with:
          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          file: extension.zip
