name: Publish Chrome Extension

on:
  push:
    branches:
      - main      # Triggers on pushes to the main branch
    tags:
      - v*.*.*    # Triggers on version tags (e.g., v1.0.0)

jobs:
  build-chrome-extension:
    name: Build Chrome Extension Artifact
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Chrome Extension Artifact
        run: |-
          # Create a ZIP of the extension files
          zip -r chrome-extension-${{ github.sha }}.zip . -x ".git*" ".github/*" "*.DS_Store"

      - name: Archive Chrome Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.sha }}.zip

  upload-extension:
    name: Upload Chrome Extension to Web Store
    runs-on: ubuntu-22.04
    needs: build-chrome-extension
    env:
      EXTENSION_ID:  ${{ secrets.CHROME_EXTENSION_VBLUR_ID }} # Replace with your Chrome Extension ID
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install Chrome Web Store CLI
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name: Upload Extension to Web Store
        run: |-
          chrome-webstore-upload upload \
            --source chrome-extension-${{ github.sha }}.zip \
            --extension-id ${{ secrets.CHROME_EXTENSION_VBLUR_ID }} \
            --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \
            --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
